=== CERTCC/SSVC/data/schema/v1/Decision_Point_Value_Selection-1-0-1.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://certcc.github.io/SSVC/data/schema/v1/Decision_Point_Value_Selection-1-0-1.schema.json",
    "$defs": {
	"id": {
            "type": "string",
            "description": "Identifier for a vulnerability could be CVE, CERT/CC VU#, OSV id, Bugtraq, GHSA etc.",
            "examples": ["CVE-1900-1234","VU#11111","GHSA-11a1-22b2-33c3"],
	    "minLength": 1
	},	
	"role": {
            "type": "string",
            "description": "Roles to define SSVC Stakeholders https://certcc.github.io/SSVC/topics/enumerating_stakeholders/",
            "examples": ["Supplier","Deployer","Coordinator"],
	    "minLength": 1
        },
	"timestamp" : {
            "description": "Date and time according to RFC 3339, section 5.6.",
            "type": "string",
	    "pattern": "^(?:[1-9]\\d{3}-[01]\\d-[0-3]\\d[Tt][0-2]\\d:[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:[Zz]|[+-][0-2]\\d:[0-5]\\d))$"
	},
	"SsvcdecisionpointselectionSchema": {
	    "description": "A down-selection of SSVC Decision Points that represent an evaluation at a specific time of a Vulnerability",
	    "properties": {
		"name": {
		    "$ref": "https://certcc.github.io/SSVC/data/schema/v1/Decision_Point-1-0-1.schema.json#/$defs/decision_point/properties/name" 		    
		},
		"namespace": {
		    "$ref": "https://certcc.github.io/SSVC/data/schema/v1/Decision_Point-1-0-1.schema.json#/$defs/decision_point/properties/namespace"		    
		},
		"values": {
		    "description": "Evaluated values of the Decision Point",
		    "title": "values",
		    "type": "array",
		    "minItems": 1,
		    "items": {
			"$ref": "https://certcc.github.io/SSVC/data/schema/v1/Decision_Point-1-0-1.schema.json#/$defs/decision_point_value/properties/name"
		    }
		},
		"version": {
		    "$ref": "https://certcc.github.io/SSVC/data/schema/v1/Decision_Point-1-0-1.schema.json#/$defs/decision_point/properties/version"		    
		}
	    },
	    "type": "object",
	    "required": [
		"name",
		"namespace",
		"values",
		"version"
	    ],
	    "additionalProperties": false
	}
    },
    "properties": {
	"id": {
	    "$ref": "#/$defs/id"
	},
	"role": {
	    "$ref": "#/$defs/role"
	},
	"schemaVersion": {
	    "$ref": "https://certcc.github.io/SSVC/data/schema/v1/Decision_Point-1-0-1.schema.json#/$defs/schemaVersion"
	},
	"timestamp": {
	    "$ref": "#/$defs/timestamp"
	},
	"selections": {
	    "description" : "An array of Decision Points and their Values that were down-selected or evaluated ",
	    "title": "selections",
	    "type": "array",
	    "minItems": 1,
	    "items": {
		"$ref": "#/$defs/SsvcdecisionpointselectionSchema"
	    }
	}
    }, 
    "type": "object",
    "required": [
	"selections",
	"id",
	"timestamp",
	"schemaVersion"
    ],
    "additionalProperties": false
}

=== CERTCC/SSVC/data/schema_examples/CVE-1900-1234-Decision_Point_Value_Selection.json
{
    "id": "CVE-1900-1234",
    "timestamp": "2021-09-29T15:29:44Z",
    "schemaVersion": "1-0-1",
    "selections": [
	{
	    "namespace": "ssvc",
	    "name": "Exploitation",
	    "version": "1.1.0",
	    "values": [
		"Active"
	    ]
	},
	{
	    "namespace": "ssvc",
	    "name": "Automatable",
	    "version": "2.0.0",
	    "values": [
		"Yes"
	    ]
	},
	{
	    "namespace": "ssvc",
	    "name": "Technical Impact",
	    "version": "1.0.0",
	    "values": [
		"Total"
	    ]
	}
    ]
}
