=== CERTCC/SSVC/data/schema/v1/Decision_Point-1-0-1.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Decision Point schema definition",
    "$id": "https://certcc.github.io/SSVC/data/schema/v1/Decision_Point-1-0-1.schema.json",
    "description": "Decision points are the basic building blocks of SSVC decision functions. Individual decision points describe a single aspect of the input to a decision function.",
    "$defs":     {
	"schemaVersion": {
            "description": "Schema version used to represent this Decision Point",
            "type": "string",
            "enum": ["1-0-1"]
        },
	"decision_point_value": {
            "type": "object",
	    "additionalProperties": false,	    
            "properties": {
                "key": {
                    "type": "string",
                    "description": "A key (a short, unique string) that can be used to identify the Decision Point/Decision Point value in a shorthand way",
		    "minLength": 1,
		    "examples": ["P", "Y"]
                },
                "name": {
                    "type": "string",
                    "description": "A short label that captures the description of the Decision Point or the Group of Decision Points.",
		    "minLength": 1,
		    "examples": ["Public PoC", "Yes"]
                },
                "description": {
                    "type": "string",
                    "description": "Description of the Decision Point Value",
		    "minLength": 1,
		    "examples": ["One of the following is true: (1) Typical public PoC exists in sources such as Metasploit or websites like ExploitDB; or (2) the vulnerability has a well-known method of exploitation.","Attackers can reliably automate steps 1-4 of the kill chain."]
                }
            },
	    "required" : [
		"key",
		"name",
		"description"
	    ]
	}, 
	"decision_point": {
	    "type": "object",
	    "additionalProperties": false,
	    "properties": {
		"schemaVersion": {
		    "$ref": "#/$defs/schemaVersion"
		},
		"namespace": {
		    "type": "string",
		    "description": "Namespace (a short, unique string): For example, \"ssvc\" or \"cvss\" to indicate the source of the decision point. See SSVC Documentation for details.",
		    "pattern": "^[a-z]{3,4}[a-z/\\.]*$",
		    "examples": ["ssvc", "cvss", "ssvc-jp", "ssvc/acme", "ssvc/example.com"]
		},
		"version": {
		    "type": "string",
		    "description": "Version (a semantic version string) that identifies this object",
		    "pattern": "^(?P<major>0|[1-9][0-9]*)\\.(?P<minor>0|[1-9][0-9]*)\\.(?P<patch>0|[1-9][0-9]*)(?:-(?P<prerelease>(?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
		    "examples": ["1.0.1", "1.0.1-alpha"]
		},
		"key": {
		    "type": "string",
		    "description": "A key (a short, unique string) that can be used to identify the Decision Point/Decision Point value in a shorthand way",
		    "minLength": 1,
		    "examples": ["E", "A"]
		},
		"name": {
		    "type": "string",
		    "description": "A short label that captures the description of the Decision Point or the Group of Decision Points.",
		    "minLength": 1,
		    "examples": ["Exploitation", "Automatable"]
		},
		"description": {
		    "type": "string",
		    "description": "Description of the Decision Point or the Group of Decision Points as defined.",
		    "minLength": 1
		},
		"values": {
		    "description": "Decision Point Values are valid results from a Decision Point",
		    "uniqueItems": true,
		    "type": "array",
		    "minItems": 1,
		    "items": {
			"$ref": "#/$defs/decision_point_value"
		    }
		}
	    },
	    "required": [
		"namespace",
		"version",
		"key",
		"name",
		"description",
		"values",
		"schemaVersion"
	    ]
	}
    },
    "$ref": "#/$defs/decision_point"
}

=== CERTCC/SSVC/data/json/decision_points/cvss/attack_vector_3_0_1.json
{
  "name": "Attack Vector",
  "description": "This metric reflects the context by which vulnerability exploitation is possible. This metric value (and consequently the resulting severity) will be larger the more remote (logically, and physically) an attacker can be in order to exploit the vulnerable system. The assumption is that the number of potential attackers for a vulnerability that could be exploited from across a network is larger than the number of potential attackers that could exploit a vulnerability requiring physical access to a device, and therefore warrants a greater severity.",
  "namespace": "cvss",
  "version": "3.0.1",
  "schemaVersion": "1-0-1",
  "key": "AV",
  "values": [
    {
      "key": "P",
      "name": "Physical",
      "description": "The attack requires the attacker to physically touch or manipulate the vulnerable system. Physical interaction may be brief (e.g., evil maid attack1) or persistent."
    },
    {
      "key": "L",
      "name": "Local",
      "description": "The vulnerable system is not bound to the network stack and the attacker’s path is via read/write/execute capabilities. Either: the attacker exploits the vulnerability by accessing the target system locally (e.g., keyboard, console), or through terminal emulation (e.g., SSH); or the attacker relies on User Interaction by another person to perform actions required to exploit the vulnerability (e.g., using social engineering techniques to trick a legitimate user into opening a malicious document)."
    },
    {
      "key": "A",
      "name": "Adjacent",
      "description": "The vulnerable system is bound to a protocol stack, but the attack is limited at the protocol level to a logically adjacent topology. This can mean an attack must be launched from the same shared proximity (e.g., Bluetooth, NFC, or IEEE 802.11) or logical network (e.g., local IP subnet), or from within a secure or otherwise limited administrative domain (e.g., MPLS, secure VPN within an administrative network zone)."
    },
    {
      "key": "N",
      "name": "Network",
      "description": "The vulnerable system is bound to the network stack and the set of possible attackers extends beyond the other options listed below, up to and including the entire Internet. Such a vulnerability is often termed “remotely exploitable” and can be thought of as an attack being exploitable at the protocol level one or more network hops away (e.g., across one or more routers)."
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/cvss/user_interaction_2_0_0.json
{
  "namespace": "cvss",
  "version": "2.0.0",
  "schemaVersion": "1-0-1",
  "key": "UI",
  "name": "User Interaction",
  "description": "This metric captures the requirement for a human user, other than the attacker, to participate in the successful compromise of the vulnerable system. This metric determines whether the vulnerability can be exploited solely at the will of the attacker, or whether a separate user (or user-initiated process) must participate in some manner. The resulting score is greatest when no user interaction is required.",
  "values": [
    {
      "key": "A",
      "name": "Active",
      "description": "Successful exploitation of this vulnerability requires a targeted user to perform specific, conscious interactions with the vulnerable system and the attacker’s payload, or the user’s interactions would actively subvert protection mechanisms which would lead to exploitation of the vulnerability."
    },
    {
      "key": "P",
      "name": "Passive",
      "description": "Successful exploitation of this vulnerability requires limited interaction by the targeted user with the vulnerable system and the attacker’s payload. These interactions would be considered involuntary and do not require that the user actively subvert protections built into the vulnerable system."
    },
    {
      "key": "N",
      "name": "None",
      "description": "The vulnerable system can be exploited without interaction from any human user, other than the attacker."
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/basic/yesno_1_0_0.json
{
  "name": "YesNo",
  "description": "A Yes/No decision point / outcome group.",
  "namespace": "basic",
  "key": "YN",
  "version": "1.0.0",
  "schemaVersion": "1-0-1",
  "values": [
    {
      "key": "N",
      "name": "No",
      "description": "No"
    },
    {
      "key": "Y",
      "name": "Yes",
      "description": "Yes"
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/cvss/modified_attack_vector_3_0_0.json
{
  "namespace": "cvss",
  "version": "3.0.0",
  "schemaVersion": "1-0-1",
  "key": "MAV",
  "name": "Modified Attack Vector",
  "description": "This metric reflects the context by which vulnerability exploitation is possible. ",
  "values": [
    {
      "key": "P",
      "name": "Physical",
      "description": "A vulnerability exploitable with Physical access requires the attacker to physically touch or manipulate the vulnerable component. Physical interaction may be brief (e.g. evil maid attack [1]) or persistent."
    },
    {
      "key": "L",
      "name": "Local",
      "description": "A vulnerability exploitable with Local access means that the vulnerable component is not bound to the network stack, and the attacker's path is via read/write/execute capabilities. In some cases, the attacker may be logged in locally in order to exploit the vulnerability, otherwise, she may rely on User Interaction to execute a malicious file."
    },
    {
      "key": "A",
      "name": "Adjacent",
      "description": "A vulnerability exploitable with adjacent network access means the vulnerable component is bound to the network stack, however the attack is limited to the same shared physical (e.g. Bluetooth, IEEE 802.11), or logical (e.g. local IP subnet) network, and cannot be performed across an OSI layer 3 boundary (e.g. a router)."
    },
    {
      "key": "N",
      "name": "Network",
      "description": "A vulnerability exploitable with network access means the vulnerable component is bound to the network stack and the attacker's path is through OSI layer 3 (the network layer). Such a vulnerability is often termed 'remotely exploitable' and can be thought of as an attack being exploitable one or more network hops away (e.g. across layer 3 boundaries from routers)."
    },
    {
      "key": "X",
      "name": "Not Defined",
      "description": "This metric value is not defined. See CVSS documentation for details."
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/system_exposure_1_0_1.json
{
  "namespace": "ssvc",
  "version": "1.0.1",
  "schemaVersion": "1-0-1",
  "key": "EXP",
  "name": "System Exposure",
  "description": "The Accessible Attack Surface of the Affected System or Service",
  "values": [
    {
      "key": "S",
      "name": "Small",
      "description": "Local service or program; highly controlled network"
    },
    {
      "key": "C",
      "name": "Controlled",
      "description": "Networked service with some access restrictions or mitigations already in place (whether locally or on the network). A successful mitigation must reliably interrupt the adversaryâ€™s attack, which requires the attack is detectable both reliably and quickly enough to respond. Controlled covers the situation in which a vulnerability can be exploited through chaining it with other vulnerabilities. The assumption is that the number of steps in the attack path is relatively low; if the path is long enough that it is implausible for an adversary to reliably execute it, then exposure should be small."
    },
    {
      "key": "O",
      "name": "Open",
      "description": "Internet or another widely accessible network where access cannot plausibly be restricted or controlled (e.g., DNS servers, web servers, VOIP servers, email servers)"
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/mission_impact_1_0_0.json
{
  "namespace": "ssvc",
  "version": "1.0.0",
  "schemaVersion": "1-0-1",
  "key": "MI",
  "name": "Mission Impact",
  "description": "Impact on Mission Essential Functions of the Organization",
  "values": [
    {
      "key": "N",
      "name": "None",
      "description": "Little to no impact"
    },
    {
      "key": "NED",
      "name": "Non-Essential Degraded",
      "description": "Degradation of non-essential functions; chronic degradation would eventually harm essential functions"
    },
    {
      "key": "MSC",
      "name": "MEF Support Crippled",
      "description": "Activities that directly support essential functions are crippled; essential functions continue for a time"
    },
    {
      "key": "MEF",
      "name": "MEF Failure",
      "description": "Any one mission essential function fails for period of time longer than acceptable; overall mission of the organization degraded but can still be accomplished for a time"
    },
    {
      "key": "MF",
      "name": "Mission Failure",
      "description": "Multiple or all mission essential functions fail; ability to recover those functions degraded; organizationâ€™s ability to deliver its overall mission fails"
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/ssvc/in_kev_1_0_0.json
{
  "name": "In KEV",
  "description": "Denotes whether a vulnerability is in the CISA Known Exploited Vulnerabilities (KEV) list.",
  "namespace": "ssvc",
  "key": "KEV",
  "version": "1.0.0",
  "schemaVersion": "1-0-1",
  "values": [
    {
      "key": "N",
      "name": "No",
      "description": "Vulnerability is not listed in KEV."
    },
    {
      "key": "Y",
      "name": "Yes",
      "description": "Vulnerability is listed in KEV."
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/automatable_2_0_0.json
{
  "namespace": "ssvc",
  "version": "2.0.0",
  "schemaVersion": "1-0-1",
  "key": "A",
  "name": "Automatable",
  "description": "Can an attacker reliably automate creating exploitation events for this vulnerability?",
  "values": [
    {
      "key": "N",
      "name": "No",
      "description": "Attackers cannot reliably automate steps 1-4 of the kill chain for this vulnerability. These steps are (1) reconnaissance, (2) weaponization, (3) delivery, and (4) exploitation."
    },
    {
      "key": "Y",
      "name": "Yes",
      "description": "Attackers can reliably automate steps 1-4 of the kill chain."
    }
  ]
}
