=== CERTCC/SSVC/data/schema/v1/Decision_Point-1-0-1.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Decision Point schema definition",
    "$id": "https://certcc.github.io/SSVC/data/schema/v1/Decision_Point-1-0-1.schema.json",
    "description": "Decision points are the basic building blocks of SSVC decision functions. Individual decision points describe a single aspect of the input to a decision function.",
    "$defs":     {
	"schemaVersion": {
            "description": "Schema version used to represent this Decision Point",
            "type": "string",
            "enum": ["1-0-1"]
        },
	"decision_point_value": {
            "type": "object",
	    "additionalProperties": false,	    
            "properties": {
                "key": {
                    "type": "string",
                    "description": "A key (a short, unique string) that can be used to identify the Decision Point/Decision Point value in a shorthand way",
		    "minLength": 1,
		    "examples": ["P", "Y"]
                },
                "name": {
                    "type": "string",
                    "description": "A short label that captures the description of the Decision Point or the Group of Decision Points.",
		    "minLength": 1,
		    "examples": ["Public PoC", "Yes"]
                },
                "description": {
                    "type": "string",
                    "description": "Description of the Decision Point Value",
		    "minLength": 1,
		    "examples": ["One of the following is true: (1) Typical public PoC exists in sources such as Metasploit or websites like ExploitDB; or (2) the vulnerability has a well-known method of exploitation.","Attackers can reliably automate steps 1-4 of the kill chain."]
                }
            },
	    "required" : [
		"key",
		"name",
		"description"
	    ]
	}, 
	"decision_point": {
	    "type": "object",
	    "additionalProperties": false,
	    "properties": {
		"schemaVersion": {
		    "$ref": "#/$defs/schemaVersion"
		},
		"namespace": {
		    "type": "string",
		    "description": "Namespace (a short, unique string): For example, \"ssvc\" or \"cvss\" to indicate the source of the decision point. See SSVC Documentation for details.",
		    "pattern": "^[a-z]{3,4}[a-z/\\.]*$",
		    "examples": ["ssvc", "cvss", "ssvc-jp", "ssvc/acme", "ssvc/example.com"]
		},
		"version": {
		    "type": "string",
		    "description": "Version (a semantic version string) that identifies this object",
		    "pattern": "^(?P<major>0|[1-9][0-9]*)\\.(?P<minor>0|[1-9][0-9]*)\\.(?P<patch>0|[1-9][0-9]*)(?:-(?P<prerelease>(?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
		    "examples": ["1.0.1", "1.0.1-alpha"]
		},
		"key": {
		    "type": "string",
		    "description": "A key (a short, unique string) that can be used to identify the Decision Point/Decision Point value in a shorthand way",
		    "minLength": 1,
		    "examples": ["E", "A"]
		},
		"name": {
		    "type": "string",
		    "description": "A short label that captures the description of the Decision Point or the Group of Decision Points.",
		    "minLength": 1,
		    "examples": ["Exploitation", "Automatable"]
		},
		"description": {
		    "type": "string",
		    "description": "Description of the Decision Point or the Group of Decision Points as defined.",
		    "minLength": 1
		},
		"values": {
		    "description": "Decision Point Values are valid results from a Decision Point",
		    "uniqueItems": true,
		    "type": "array",
		    "minItems": 1,
		    "items": {
			"$ref": "#/$defs/decision_point_value"
		    }
		}
	    },
	    "required": [
		"namespace",
		"version",
		"key",
		"name",
		"description",
		"values",
		"schemaVersion"
	    ]
	}
    },
    "$ref": "#/$defs/decision_point"
}

=== CERTCC/SSVC/data/json/decision_points/nist/adversary_capability_1_0_0.json
{
  "name": "Adversary Capability",
  "description": "Characteristics of adversary capability",
  "namespace": "nist",
  "version": "1.0.0",
  "schemaVersion": "1-0-1",
  "key": "AC",
  "values": [
    {
      "key": "VL",
      "name": "Very Low",
      "description": "The adversary has very limited resources, expertise, and opportunities to support a successful attack."
    },
    {
      "key": "L",
      "name": "Low",
      "description": "The adversary has limited resources, expertise, and opportunities to support a successful attack."
    },
    {
      "key": "M",
      "name": "Moderate",
      "description": "The adversary has moderate resources, expertise, and opportunities to support multiple successful attacks."
    },
    {
      "key": "H",
      "name": "High",
      "description": "The adversary has a sophisticated level of expertise, with significant resources and opportunities to support multiple successful coordinated attacks."
    },
    {
      "key": "VH",
      "name": "Very High",
      "description": "The adversary has a very sophisticated level of expertise, is well-resourced, and can generate opportunities to support multiple successful, continuous, and coordinated attacks."
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/cvss/safety_1_0_0.json
{
  "namespace": "cvss",
  "version": "1.0.0",
  "schemaVersion": "1-0-1",
  "key": "S",
  "name": "Safety",
  "description": "The Safety decision point is a measure of the potential for harm to humans or the environment.",
  "values": [
    {
      "key": "X",
      "name": "Not Defined",
      "description": "This metric value is not defined. See CVSS documentation for details."
    },
    {
      "key": "P",
      "name": "Present",
      "description": "Consequences of the vulnerability meet definition of IEC 61508 consequence categories of \"marginal,\" \"critical,\" or \"catastrophic.\""
    },
    {
      "key": "N",
      "name": "Negligible",
      "description": "Consequences of the vulnerability meet definition of IEC 61508 consequence category \"negligible.\""
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/cvss/target_distribution_1_0_0.json
{
  "namespace": "cvss",
  "version": "1.0.0",
  "schemaVersion": "1-0-1",
  "key": "TD",
  "name": "Target Distribution",
  "description": "This metric measures the relative size of the field of target systems susceptible to the vulnerability. It is meant as an environment-specific indicator in order to approximate the percentage of systems within the environment that could be affected by the vulnerability.",
  "values": [
    {
      "key": "N",
      "name": "None",
      "description": "No target systems exist, or targets are so highly specialized that they only exist in a laboratory setting. Effectively 0% of the environment is at risk."
    },
    {
      "key": "L",
      "name": "Low",
      "description": "Targets exist inside the environment, but on a small scale. Between 1% - 15% of the total environment is at risk."
    },
    {
      "key": "M",
      "name": "Medium",
      "description": "Targets exist inside the environment, but on a medium scale. Between 16% - 49% of the total environment is at risk."
    },
    {
      "key": "H",
      "name": "High",
      "description": "Targets exist inside the environment on a considerable scale. Between 50% - 100% of the total environment is considered at risk."
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/nist/adversary_intent_1_0_0.json
{
  "name": "Adversary Intent",
  "description": "Characteristics of adversary intent",
  "namespace": "nist",
  "version": "1.0.0",
  "schemaVersion": "1-0-1",
  "key": "AI",
  "values": [
    {
      "key": "VL",
      "name": "Very Low",
      "description": "The adversary seeks to usurp, disrupt, or deface the organization’s cyber resources, and does so without concern about attack detection/disclosure of tradecraft."
    },
    {
      "key": "L",
      "name": "Low",
      "description": "The adversary actively seeks to obtain critical or sensitive information or to usurp/disrupt the organization’s cyber resources, and does so without concern about attack detection/disclosure of tradecraft."
    },
    {
      "key": "M",
      "name": "Moderate",
      "description": "The adversary seeks to obtain or modify specific critical or sensitive information or usurp/disrupt the organization’s cyber resources by establishing a foothold in the organization’s information systems or infrastructure. The adversary is concerned about minimizing attack detection/disclosure of tradecraft, particularly when carrying out attacks over long time periods. The adversary is willing to impede aspects of the organization’s missions/business functions to achieve these ends."
    },
    {
      "key": "H",
      "name": "High",
      "description": "The adversary seeks to undermine/impede critical aspects of a core mission or business function, program, or enterprise, or place itself in a position to do so in the future, by maintaining a presence in the organization’s information systems or infrastructure. The adversary is very concerned about minimizing attack detection/disclosure of tradecraft, particularly while preparing for future attacks."
    },
    {
      "key": "VH",
      "name": "Very High",
      "description": "The adversary seeks to undermine, severely impede, or destroy a core mission or business function, program, or enterprise by exploiting a presence in the organization’s information systems or infrastructure. The adversary is concerned about disclosure of tradecraft only to the extent that it would impede its ability to complete stated goals."
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/cvss/modified_integrity_impact_to_the_subsequent_system_1_0_0.json
{
  "namespace": "cvss",
  "version": "1.0.0",
  "schemaVersion": "1-0-1",
  "key": "MSI",
  "name": "Modified Integrity Impact to the Subsequent System",
  "description": "This metric measures the impact to integrity of a successfully exploited vulnerability. Integrity refers to the trustworthiness and veracity of information. Integrity of a system is impacted when an attacker causes unauthorized modification of system data. Integrity is also impacted when a system user can repudiate critical actions taken in the context of the system (e.g. due to insufficient logging). The resulting score is greatest when the consequence to the system is highest.",
  "values": [
    {
      "key": "N",
      "name": "Negligible",
      "description": "There is no loss of integrity within the Subsequent System or all integrity impact is constrained to the Vulnerable System."
    },
    {
      "key": "L",
      "name": "Low",
      "description": "Modification of data is possible, but the attacker does not have control over the consequence of a modification, or the amount of modification is limited. The data modification does not have a direct, serious impact to the Subsequent System."
    },
    {
      "key": "H",
      "name": "High",
      "description": "There is a total loss of integrity, or a complete loss of protection. For example, the attacker is able to modify any/all files protected by the Subsequent System. Alternatively, only some files can be modified, but malicious modification would present a direct, serious consequence to the Subsequent System."
    },
    {
      "key": "X",
      "name": "Not Defined",
      "description": "This metric value is not defined. See CVSS documentation for details."
    },
    {
      "key": "S",
      "name": "Safety",
      "description": "The Safety metric value measures the impact regarding the Safety of a human actor or participant that can be predictably injured as a result of the vulnerability being exploited."
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/nist/threat_event_relevance_1_0_0.json
{
  "name": "Threat Event Relevance",
  "description": "Relevance of threat events",
  "namespace": "nist",
  "version": "1.0.0",
  "schemaVersion": "1-0-1",
  "key": "TER",
  "values": [
    {
      "key": "NA",
      "name": "N/A",
      "description": "The threat event or TTP is not currently applicable. For example, a threat event or TTP could assume specific technologies, architectures, or processes that are not present in the organization, mission/business process, EA segment, or information system; or predisposing conditions that are not present (e.g., location in a flood plain). Alternately, if the organization is using detailed or specific threat information, a threat event or TTP could be deemed inapplicable because information indicates that no adversary is expected to initiate the threat event or use the TTP."
    },
    {
      "key": "PS",
      "name": "Possible",
      "description": "The threat event or TTP has been described by a somewhat credible source."
    },
    {
      "key": "P",
      "name": "Predicted",
      "description": "The threat event or TTP has been predicted by a trusted source."
    },
    {
      "key": "A",
      "name": "Anticipated",
      "description": "The threat event or TTP has been reported by a trusted source."
    },
    {
      "key": "E",
      "name": "Expected",
      "description": "The threat event or TTP has been seen by the organizationâ€™s peers or partners."
    },
    {
      "key": "C",
      "name": "Confirmed",
      "description": "The threat event or TTP has been seen by the organization."
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/cvss/confidentiality_impact_2_0_0.json
{
  "name": "Confidentiality Impact",
  "description": "This metric measures the impact to the confidentiality of the information resources managed by a software component due to a successfully exploited vulnerability.",
  "namespace": "cvss",
  "version": "2.0.0",
  "schemaVersion": "1-0-1",
  "key": "C",
  "values": [
    {
      "key": "N",
      "name": "None",
      "description": "There is no loss of confidentiality within the impacted component."
    },
    {
      "key": "L",
      "name": "Low",
      "description": "There is some loss of confidentiality. Access to some restricted information is obtained, but the attacker does not have control over what information is obtained, or the amount or kind of loss is constrained. The information disclosure does not cause a direct, serious loss to the impacted component."
    },
    {
      "key": "H",
      "name": "High",
      "description": "There is total loss of confidentiality, resulting in all resources within the impacted component being divulged to the attacker. Alternatively, access to only some restricted information is obtained, but the disclosed information presents a direct, serious impact. For example, an attacker steals the administrator's password, or private encryption keys of a web server."
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/cvss/access_vector_2_0_0.json
{
  "namespace": "cvss",
  "version": "2.0.0",
  "schemaVersion": "1-0-1",
  "key": "AV",
  "name": "Access Vector",
  "description": "This metric reflects the context by which vulnerability exploitation is possible.",
  "values": [
    {
      "key": "L",
      "name": "Local",
      "description": "A vulnerability exploitable with only local access requires the attacker to have either physical access to the vulnerable system or a local (shell) account."
    },
    {
      "key": "A",
      "name": "Adjacent Network",
      "description": "A vulnerability exploitable with adjacent network access requires the attacker to have access to either the broadcast or collision domain of the vulnerable software."
    },
    {
      "key": "N",
      "name": "Network",
      "description": "A vulnerability exploitable with network access means the vulnerable software is bound to the network stack and the attacker does not require local network access or local access. Such a vulnerability is often termed 'remotely exploitable'."
    }
  ]
}
