=== CERTCC/SSVC/data/schema/v1/Decision_Point-1-0-1.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Decision Point schema definition",
    "$id": "https://certcc.github.io/SSVC/data/schema/v1/Decision_Point-1-0-1.schema.json",
    "description": "Decision points are the basic building blocks of SSVC decision functions. Individual decision points describe a single aspect of the input to a decision function.",
    "$defs":     {
	"schemaVersion": {
            "description": "Schema version used to represent this Decision Point",
            "type": "string",
            "enum": ["1-0-1"]
        },
	"decision_point_value": {
            "type": "object",
	    "additionalProperties": false,	    
            "properties": {
                "key": {
                    "type": "string",
                    "description": "A key (a short, unique string) that can be used to identify the Decision Point/Decision Point value in a shorthand way",
		    "minLength": 1,
		    "examples": ["P", "Y"]
                },
                "name": {
                    "type": "string",
                    "description": "A short label that captures the description of the Decision Point or the Group of Decision Points.",
		    "minLength": 1,
		    "examples": ["Public PoC", "Yes"]
                },
                "description": {
                    "type": "string",
                    "description": "Description of the Decision Point Value",
		    "minLength": 1,
		    "examples": ["One of the following is true: (1) Typical public PoC exists in sources such as Metasploit or websites like ExploitDB; or (2) the vulnerability has a well-known method of exploitation.","Attackers can reliably automate steps 1-4 of the kill chain."]
                }
            },
	    "required" : [
		"key",
		"name",
		"description"
	    ]
	}, 
	"decision_point": {
	    "type": "object",
	    "additionalProperties": false,
	    "properties": {
		"schemaVersion": {
		    "$ref": "#/$defs/schemaVersion"
		},
		"namespace": {
		    "type": "string",
		    "description": "Namespace (a short, unique string): For example, \"ssvc\" or \"cvss\" to indicate the source of the decision point. See SSVC Documentation for details.",
		    "pattern": "^[a-z]{3,4}[a-z/\\.]*$",
		    "examples": ["ssvc", "cvss", "ssvc-jp", "ssvc/acme", "ssvc/example.com"]
		},
		"version": {
		    "type": "string",
		    "description": "Version (a semantic version string) that identifies this object",
		    "pattern": "^(?P<major>0|[1-9][0-9]*)\\.(?P<minor>0|[1-9][0-9]*)\\.(?P<patch>0|[1-9][0-9]*)(?:-(?P<prerelease>(?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
		    "examples": ["1.0.1", "1.0.1-alpha"]
		},
		"key": {
		    "type": "string",
		    "description": "A key (a short, unique string) that can be used to identify the Decision Point/Decision Point value in a shorthand way",
		    "minLength": 1,
		    "examples": ["E", "A"]
		},
		"name": {
		    "type": "string",
		    "description": "A short label that captures the description of the Decision Point or the Group of Decision Points.",
		    "minLength": 1,
		    "examples": ["Exploitation", "Automatable"]
		},
		"description": {
		    "type": "string",
		    "description": "Description of the Decision Point or the Group of Decision Points as defined.",
		    "minLength": 1
		},
		"values": {
		    "description": "Decision Point Values are valid results from a Decision Point",
		    "uniqueItems": true,
		    "type": "array",
		    "minItems": 1,
		    "items": {
			"$ref": "#/$defs/decision_point_value"
		    }
		}
	    },
	    "required": [
		"namespace",
		"version",
		"key",
		"name",
		"description",
		"values",
		"schemaVersion"
	    ]
	}
    },
    "$ref": "#/$defs/decision_point"
}

=== CERTCC/SSVC/data/json/decision_points/x_basic/do_schedule_delegate_delete_1_0_0.json
{
  "name": "Do, Schedule, Delegate, Delete",
  "description": "The Eisenhower outcome group.",
  "namespace": "x_basic",
  "version": "1.0.0",
  "schemaVersion": "1-0-1",
  "key": "IKE",
  "values": [
    {
      "key": "D",
      "name": "Delete",
      "description": "Delete"
    },
    {
      "key": "G",
      "name": "Delegate",
      "description": "Delegate"
    },
    {
      "key": "S",
      "name": "Schedule",
      "description": "Schedule"
    },
    {
      "key": "O",
      "name": "Do",
      "description": "Do"
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/cvss/availability_impact_2_0_1.json
{"namespace": "cvss", "version": "2.0.1", "schemaVersion": "1-0-1", "key": "A", "name": "Availability Impact", "description": "This metric measures the impact to the availability of the impacted system resulting from a successfully exploited vulnerability.", "values": [{"key": "N", "name": "None", "description": "There is no impact to availability within the Vulnerable System."}, {"key": "L", "name": "Low", "description": "There is reduced performance or interruptions in resource availability. Even if repeated exploitation of the vulnerability is possible, the attacker does not have the ability to completely deny service to legitimate users. The resources in the Vulnerable System are either partially available all of the time, or fully available only some of the time, but overall there is no direct, serious consequence to the Vulnerable System."}, {"key": "H", "name": "High", "description": "There is total loss of availability, resulting in the attacker being able to fully deny access to resources in the impacted component; this loss is either sustained (while the attacker continues to deliver the attack) or persistent (the condition persists even after the attack has completed)."}]}

=== CERTCC/SSVC/data/json/decision_points/x_basic/value_complexity_1_0_0.json
{
  "name": "Value, Complexity",
  "description": "The Value/Complexity outcome group.",
  "namespace": "x_basic",
  "version": "1.0.0",
  "schemaVersion": "1-0-1",
  "key": "VALUE_COMPLEXITY",
  "values": [
    {
      "key": "D",
      "name": "Drop",
      "description": "Drop"
    },
    {
      "key": "R",
      "name": "Reconsider Later",
      "description": "Reconsider Later"
    },
    {
      "key": "E",
      "name": "Easy Win",
      "description": "Easy Win"
    },
    {
      "key": "F",
      "name": "Do First",
      "description": "Do First"
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/cvss/availability_impact_2_0_0.json
{
  "namespace": "cvss",
  "version": "2.0.0",
  "schemaVersion": "1-0-1",
  "key": "A",
  "name": "Availability Impact",
  "description": "This metric measures the impact to availability of a successfully exploited vulnerability.",
  "values": [
    {
      "key": "N",
      "name": "None",
      "description": "There is no impact to the availability of the system."
    },
    {
      "key": "L",
      "name": "Low",
      "description": "There is reduced performance or interruptions in resource availability."
    },
    {
      "key": "H",
      "name": "High",
      "description": "There is total loss of availability, resulting in the attacker being able to fully deny access to resources in the impacted component; this loss is either sustained (while the attacker continues to deliver the attack) or persistent (the condition persists even after the attack has completed)."
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/cvss/remediation_level_1_0_0.json
{
  "namespace": "cvss",
  "version": "1.0.0",
  "schemaVersion": "1-0-1",
  "key": "RL",
  "name": "Remediation Level",
  "description": "This metric measures the remediation status of a vulnerability.",
  "values": [
    {
      "key": "OF",
      "name": "Official Fix",
      "description": "A complete vendor solution is available. Either the vendor has issued the final, official patch which eliminates the vulnerability or an upgrade that is not vulnerable is available."
    },
    {
      "key": "TF",
      "name": "Temporary Fix",
      "description": "There is an official but temporary fix available. This includes instances where the vendor issues a temporary hotfix, tool or official workaround."
    },
    {
      "key": "W",
      "name": "Workaround",
      "description": "There is an unofficial, non-vendor solution available. In some cases, users of the affected technology will create a patch of their own or provide steps to work around or otherwise mitigate against the vulnerability. When it is generally accepted that these unofficial fixes are adequate in plugging the hole for the mean time and no official remediation is available, this value can be set."
    },
    {
      "key": "U",
      "name": "Unavailable",
      "description": "There is either no solution available or it is impossible to apply."
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/cvss/confidentiality_requirement_1_0_0.json
{
  "namespace": "cvss",
  "version": "1.0.0",
  "schemaVersion": "1-0-1",
  "key": "CR",
  "name": "Confidentiality Requirement",
  "description": "This metric measures the impact to the confidentiality of a successfully exploited vulnerability.",
  "values": [
    {
      "key": "L",
      "name": "Low",
      "description": "Loss of confidentiality is likely to have only a limited adverse effect on the organization or individuals associated with the organization (e.g., employees, customers)."
    },
    {
      "key": "M",
      "name": "Medium",
      "description": "Loss of confidentiality is likely to have a serious adverse effect on the organization or individuals associated with the organization (e.g., employees, customers)."
    },
    {
      "key": "H",
      "name": "High",
      "description": "Loss of confidentiality is likely to have a catastrophic adverse effect on the organization or individuals associated with the organization (e.g., employees, customers)."
    },
    {
      "key": "ND",
      "name": "Not Defined",
      "description": "This metric value is not defined. See CVSS documentation for details."
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/supplier_engagement_1_0_0.json
{
  "namespace": "ssvc",
  "version": "1.0.0",
  "schemaVersion": "1-0-1",
  "key": "SE",
  "name": "Supplier Engagement",
  "description": "Is the supplier responding to the reporter’s contact effort and actively participating in the coordination effort?",
  "values": [
    {
      "key": "A",
      "name": "Active",
      "description": "The supplier is responding to the reporter’s contact effort and actively participating in the coordination effort."
    },
    {
      "key": "U",
      "name": "Unresponsive",
      "description": "The supplier is not responding to the reporter’s contact effort and not actively participating in the coordination effort."
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/cvss/access_complexity_1_0_0.json
{
  "namespace": "cvss",
  "version": "1.0.0",
  "schemaVersion": "1-0-1",
  "key": "AC",
  "name": "Access Complexity",
  "description": "This metric measures the complexity of the attack required to exploit the vulnerability once an attacker has gained access to the target system.",
  "values": [
    {
      "key": "L",
      "name": "Low",
      "description": "Specialized access conditions or extenuating circumstances do not exist; the system is always exploitable."
    },
    {
      "key": "H",
      "name": "High",
      "description": "Specialized access conditions exist; for example: the system is exploitable during specific windows of time (a race condition), the system is exploitable under specific circumstances (nondefault configurations), or the system is exploitable with victim interaction (vulnerability exploitable only if user opens e-mail)"
    }
  ]
}
