=== CERTCC/SSVC/data/schema/v1/Outcome_Group-1-0-1.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Outcome Group/Set schema definition",
    "$id": "https://certcc.github.io/SSVC/data/schema/v1/Outcome-1-0-1.schema.json",
    "description": "An outcome is the result of making a decision. Outcomes are often tailored specifically to the stakeholder context in which the decision is being made. We call the set of possible outcomes for a decision an Outcome Set.",
    "$defs":     {
	"schemaVersion": {
            "description": "Schema version used to represent this Outcome Group",
            "type": "string",
            "enum": ["1-0-1"]
        },
	"outcome_value": {
            "type": "object",
	    "additionalProperties": false,	    
            "properties": {
                "key": {
                    "type": "string",
                    "description": "A key (a short, unique string) that can be used to identify the Outcome in a shorthand way"
                },
                "name": {
                    "type": "string",
                    "description": "A short label that captures the description of the Decision Point or the Group of Decision Points."
                },
                "description": {
                    "type": "string",
                    "description": "Description of the Decision Point Value"
                }
            },
	    "required" : [
		"key",
		"name",
		"description"
	    ]
	},
	"outcome_group": {
	    "type": "object",
	    "additionalProperties": false,
	    "properties": {
		"schemaVersion": {
		    "$ref": "#/$defs/schemaVersion"
		},
		"version": {
		    "type": "string",
		    "description": "Version (a semantic version string) that identifies this object"
		},
		"name": {
		    "type": "string",
		    "description": "A short label that captures the description of the group of Outcomes"
		},
		"description": {
		    "type": "string",
		    "description": " Description of the of group of Outcomes."
		},		
		"outcomes": {
		    "description": "Collection Set of Outcomes.",
		    "uniqueItems": true,
		    "type": "array",
		    "minItems": 2,
		    "items": {
			"$ref": "#/$defs/outcome_value"
		    }
		}
	    },
	    "required": [
		"version",
		"name",
		"description",
		"outcomes",
		"schemaVersion"
	    ]
	}
    },
    "$ref": "#/$defs/outcome_group"
}

=== CERTCC/SSVC/data/json/outcomes/THE_PARANOIDS.json
{
  "version": "1.0.0",
  "schemaVersion": "1-0-1",
  "name": "theParanoids",
  "description": "PrioritizedRiskRemediation outcome group based on TheParanoids.",
  "outcomes": [
    {
      "key": "5",
      "name": "Track 5",
      "description": "Track"
    },
    {
      "key": "4",
      "name": "Track Closely 4",
      "description": "Track Closely"
    },
    {
      "key": "3",
      "name": "Attend 3",
      "description": "Attend"
    },
    {
      "key": "2",
      "name": "Attend 2",
      "description": "Attend"
    },
    {
      "key": "1",
      "name": "Act 1",
      "description": "Act"
    },
    {
      "key": "0",
      "name": "Act ASAP 0",
      "description": "Act ASAP"
    }
  ]
}

=== CERTCC/SSVC/data/json/outcomes/VALUE_COMPLEXITY.json
{
  "version": "1.0.0",
  "schemaVersion": "1-0-1",
  "name": "Value, Complexity",
  "description": "The Value/Complexity outcome group.",
  "outcomes": [
    {
      "key": "D",
      "name": "Drop",
      "description": "Drop"
    },
    {
      "key": "R",
      "name": "Reconsider Later",
      "description": "Reconsider Later"
    },
    {
      "key": "E",
      "name": "Easy Win",
      "description": "Easy Win"
    },
    {
      "key": "F",
      "name": "Do First",
      "description": "Do First"
    }
  ]
}

=== CERTCC/SSVC/data/json/outcomes/MOSCOW.json
{
  "version": "1.0.0",
  "schemaVersion": "1-0-1",
  "name": "Must, Should, Could, Won't",
  "description": "The Moscow outcome group.",
  "outcomes": [
    {
      "key": "W",
      "name": "Won't",
      "description": "Won't"
    },
    {
      "key": "C",
      "name": "Could",
      "description": "Could"
    },
    {
      "key": "S",
      "name": "Should",
      "description": "Should"
    },
    {
      "key": "M",
      "name": "Must",
      "description": "Must"
    }
  ]
}

=== CERTCC/SSVC/data/json/outcomes/COORDINATE.json
{
  "version": "1.0.0",
  "schemaVersion": "1-0-1",
  "name": "Decline, Track, Coordinate",
  "description": "The coordinate outcome group.",
  "outcomes": [
    {
      "key": "D",
      "name": "Decline",
      "description": "Decline"
    },
    {
      "key": "T",
      "name": "Track",
      "description": "Track"
    },
    {
      "key": "C",
      "name": "Coordinate",
      "description": "Coordinate"
    }
  ]
}

=== CERTCC/SSVC/data/json/outcomes/DSOI.json
{
  "version": "1.0.0",
  "schemaVersion": "1-0-1",
  "name": "Defer, Scheduled, Out-of-Cycle, Immediate",
  "description": "The original SSVC outcome group.",
  "outcomes": [
    {
      "key": "D",
      "name": "Defer",
      "description": "Defer"
    },
    {
      "key": "S",
      "name": "Scheduled",
      "description": "Scheduled"
    },
    {
      "key": "O",
      "name": "Out-of-Cycle",
      "description": "Out-of-Cycle"
    },
    {
      "key": "I",
      "name": "Immediate",
      "description": "Immediate"
    }
  ]
}

=== CERTCC/SSVC/data/json/outcomes/CISA.json
{
  "version": "1.0.0",
  "schemaVersion": "1-0-1",
  "name": "CISA Levels",
  "description": "The CISA outcome group. CISA uses its own SSVC decision tree model to prioritize relevant vulnerabilities into four possible decisions: Track, Track*, Attend, and Act.",
  "outcomes": [
    {
      "key": "T",
      "name": "Track",
      "description": "The vulnerability does not require action at this time. The organization would continue to track the vulnerability and reassess it if new information becomes available. CISA recommends remediating Track vulnerabilities within standard update timelines."
    },
    {
      "key": "T*",
      "name": "Track*",
      "description": "The vulnerability contains specific characteristics that may require closer monitoring for changes. CISA recommends remediating Track* vulnerabilities within standard update timelines."
    },
    {
      "key": "A",
      "name": "Attend",
      "description": "The vulnerability requires attention from the organization's internal, supervisory-level individuals. Necessary actions may include requesting assistance or information about the vulnerability and may involve publishing a notification, either internally and/or externally, about the vulnerability. CISA recommends remediating Attend vulnerabilities sooner than standard update timelines."
    },
    {
      "key": "A",
      "name": "Act",
      "description": "The vulnerability requires attention from the organization's internal, supervisory-level and leadership-level individuals. Necessary actions include requesting assistance or information about the vulnerability, as well as publishing a notification either internally and/or externally. Typically, internal groups would meet to determine the overall response and then execute agreed upon actions. CISA recommends remediating Act vulnerabilities as soon as possible."
    }
  ]
}

=== CERTCC/SSVC/data/json/outcomes/PUBLISH.json
{
  "version": "1.0.0",
  "schemaVersion": "1-0-1",
  "name": "Publish, Do Not Publish",
  "description": "The publish outcome group.",
  "outcomes": [
    {
      "key": "N",
      "name": "Do Not Publish",
      "description": "Do Not Publish"
    },
    {
      "key": "P",
      "name": "Publish",
      "description": "Publish"
    }
  ]
}

=== CERTCC/SSVC/data/json/outcomes/CVSS.json
{
  "version": "1.0.0",
  "schemaVersion": "1-0-1",
  "name": "CVSS Levels",
  "description": "The CVSS outcome group.",
  "outcomes": [
    {
      "key": "L",
      "name": "Low",
      "description": "Low"
    },
    {
      "key": "M",
      "name": "Medium",
      "description": "Medium"
    },
    {
      "key": "H",
      "name": "High",
      "description": "High"
    },
    {
      "key": "C",
      "name": "Critical",
      "description": "Critical"
    }
  ]
}
