=== CERTCC/SSVC/data/schema/Decision_Point.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Decision Point schema definition",
    "$id": "https://github.com/CERTCC/SSVC/tree/main/data/schema/Decision_Point.schema.json",
    "description": "Decision points are the basic building blocks of SSVC decision functions. Individual decision points describe a single aspect of the input to a decision function.",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "namespace": {
            "type": "string",
            "description": "Namespace (a short, unique string): For example, \"ssvc\" or \"cvss\" to indicate the source of the decision point"
        },
        "version": {
            "type": "string",
            "description": "Version (a semantic version string) that identifies this object"
        },
        "key": {
            "type": "string",
            "description": "A key (a short, unique string) that can be used to identify the Decision Point/Decision Point value in a shorthand way"
        },
        "name": {
            "type": "string",
            "description": "A short label that captures the description of the Decision Point or the Group of Decision Points."
        },
        "description": {
            "type": "string",
            "description": "Description of the Decision Point or the Group of Decision Points."
        },
        "values": {
            "description": "Decision Point Values are valid results from a Decision Point",
            "uniqueItems": true,
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "key": {
                        "type": "string",
                        "description": "A key (a short, unique string) that can be used to identify the Decision Point/Decision Point value in a shorthand way"
                    },
                    "name": {
                        "type": "string",
                        "description": "A short label that captures the description of the Decision Point or the Group of Decision Points."
                    },
                    "description": {
                        "type": "string",
                        "description": "Description of the Decision Point or the Group of Decision Points."
                    }
                }
            }
        }
    },
    "required": [
        "namespace",
        "version",
        "key",
        "name",
        "description",
        "values"
    ]
}

=== CERTCC/SSVC/docs/reference/examples/automatable.json
{
  "namespace": "ssvc",
  "version": "1.0.0",
  "name": "Automatable",
  "description": "Can an attacker reliably automate creating exploitation events for this vulnerability?",
  "key": "A",
  "values": [
    {
      "name": "No",
      "description": "Attackers cannot reliably automate steps 1-4 of the kill chain for this vulnerability. These steps are (1) reconnaissance, (2) weaponization, (3) delivery, and (4) exploitation.",
      "key": "N"
    },
    {
      "name": "Yes",
      "description": "Attackers can reliably automate steps 1-4 of the kill chain.",
      "key": "Y"
    }
  ]
}

=== CERTCC/SSVC/docs/reference/examples/report_credibility.json
{
  "namespace": "ssvc",
  "version": "1.0.0",
  "name": "Report Credibility",
  "description": "Is the report credible?",
  "key": "RC",
  "values": [
    {
      "name": "Credible",
      "description": "The report is credible.",
      "key": "C"
    },
    {
      "name": "Not Credible",
      "description": "The report is not credible.",
      "key": "NC"
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/utility_1_0_1.json
{
  "namespace": "ssvc",
  "version": "1.0.1",
  "key": "U",
  "name": "Utility",
  "description": "The Usefulness of the Exploit to the Adversary",
  "values": [
    {
      "key": "L",
      "name": "Laborious",
      "description": "Automatable:No and Value Density:Diffuse"
    },
    {
      "key": "E",
      "name": "Efficient",
      "description": "Automatable:Yes and Value Density:Diffuse OR Automatable:No  and Value Density:Concentrated"
    },
    {
      "key": "S",
      "name": "Super Effective",
      "description": "Automatable:Yes and Value Density:Concentrated"
    }
  ]
}

=== CERTCC/SSVC/docs/reference/examples/supplier_cardinality.json
{
  "namespace": "ssvc",
  "version": "1.0.0",
  "name": "Supplier Cardinality",
  "description": "How many suppliers are responsible for the vulnerable component and its remediation or mitigation plan?",
  "key": "SC",
  "values": [
    {
      "name": "One",
      "description": "There is only one supplier of the vulnerable component.",
      "key": "O"
    },
    {
      "name": "Multiple",
      "description": "There are multiple suppliers of the vulnerable component.",
      "key": "M"
    }
  ]
}

=== CERTCC/SSVC/docs/reference/examples/report_public.json
{
  "namespace": "ssvc",
  "version": "1.0.0",
  "name": "Report Public",
  "description": "Is a viable report of the details of the vulnerability already publicly available?",
  "key": "RP",
  "values": [
    {
      "name": "No",
      "description": "No public report of the vulnerability exists.",
      "key": "N"
    },
    {
      "name": "Yes",
      "description": "A public report of the vulnerability exists.",
      "key": "Y"
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/human_impact_1_0_0.json
{
  "namespace": "ssvc",
  "version": "1.0.0",
  "key": "HI",
  "name": "Human Impact",
  "description": "Human Impact is a combination of Safety and Mission impacts.",
  "values": [
    {
      "key": "L",
      "name": "Low",
      "description": "Safety=None/Minor, Mission=None/Degraded/Crippled"
    },
    {
      "key": "M",
      "name": "Medium",
      "description": "Safety=None/Minor, Mission=MEF Failure OR Safety=Major, Mission=None/Degraded/Crippled"
    },
    {
      "key": "H",
      "name": "High",
      "description": "Safety=Hazardous, Mission=None/Degraded/Crippled/MEF Failure OR Safety=Major, Mission=MEF Failure"
    },
    {
      "key": "VH",
      "name": "Very High",
      "description": "Safety=Catastrophic OR Mission=Mission Failure"
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/virulence_1_0_0.json
{
  "namespace": "ssvc",
  "version": "1.0.0",
  "key": "V",
  "name": "Virulence",
  "description": "The speed at which the vulnerability can be exploited.",
  "values": [
    {
      "key": "S",
      "name": "Slow",
      "description": "Steps 1-4 of the kill chain cannot be reliably automated for this vulnerability for some reason. These steps are reconnaissance, weaponization, delivery, and exploitation."
    },
    {
      "key": "R",
      "name": "Rapid",
      "description": "Steps 1-4 of the of the kill chain can be reliably automated. If the vulnerability allows remote code execution or command injection, the default response should be rapid."
    }
  ]
}

=== CERTCC/SSVC/docs/reference/examples/public_safety_impact.json
{
  "namespace": "ssvc",
  "version": "1.0.0",
  "name": "Public Safety Impact",
  "description": "A coarse-grained representation of impact to public safety.",
  "key": "PSI",
  "values": [
    {
      "name": "Minimal",
      "description": "Safety impact of None or Minor.",
      "key": "M"
    },
    {
      "name": "Significant",
      "description": "Safety impact of Major, Hazardous, or Catastrophic.",
      "key": "S"
    }
  ]
}
