=== CERTCC/SSVC/data/schema/Decision_Point.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Decision Point schema definition",
    "$id": "https://github.com/CERTCC/SSVC/tree/main/data/schema/Decision_Point.schema.json",
    "description": "Decision points are the basic building blocks of SSVC decision functions. Individual decision points describe a single aspect of the input to a decision function.",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "namespace": {
            "type": "string",
            "description": "Namespace (a short, unique string): For example, \"ssvc\" or \"cvss\" to indicate the source of the decision point"
        },
        "version": {
            "type": "string",
            "description": "Version (a semantic version string) that identifies this object"
        },
        "key": {
            "type": "string",
            "description": "A key (a short, unique string) that can be used to identify the Decision Point/Decision Point value in a shorthand way"
        },
        "name": {
            "type": "string",
            "description": "A short label that captures the description of the Decision Point or the Group of Decision Points."
        },
        "description": {
            "type": "string",
            "description": "Description of the Decision Point or the Group of Decision Points."
        },
        "values": {
            "description": "Decision Point Values are valid results from a Decision Point",
            "uniqueItems": true,
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "key": {
                        "type": "string",
                        "description": "A key (a short, unique string) that can be used to identify the Decision Point/Decision Point value in a shorthand way"
                    },
                    "name": {
                        "type": "string",
                        "description": "A short label that captures the description of the Decision Point or the Group of Decision Points."
                    },
                    "description": {
                        "type": "string",
                        "description": "Description of the Decision Point or the Group of Decision Points."
                    }
                }
            }
        }
    },
    "required": [
        "namespace",
        "version",
        "key",
        "name",
        "description",
        "values"
    ]
}

=== CERTCC/SSVC/docs/reference/examples/value_density.json
{
  "namespace": "ssvc",
  "version": "1.0.0",
  "name": "Value Density",
  "description": "The concentration of value in the target",
  "key": "VD",
  "values": [
    {
      "name": "Diffuse",
      "description": "The system that contains the vulnerable component has limited resources. That is, the resources that the adversary will gain control over with a single exploitation event are relatively small.",
      "key": "D"
    },
    {
      "name": "Concentrated",
      "description": "The system that contains the vulnerable component is rich in resources. Heuristically, such systems are often the direct responsibility of \u201csystem operators\u201d rather than users.",
      "key": "C"
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/mission_and_well-being_impact_1_0_0.json
{
  "namespace": "ssvc",
  "version": "1.0.0",
  "key": "MWI",
  "name": "Mission and Well-Being Impact",
  "description": "Mission and Well-Being Impact is a combination of Mission Prevalence and Public Well-Being Impact.",
  "values": [
    {
      "key": "L",
      "name": "Low",
      "description": "Mission Prevalence:Minimal AND Public Well-Being Impact:Minimal"
    },
    {
      "key": "M",
      "name": "Medium",
      "description": "Mission Prevalence:Support AND Public Well-Being Impact:(Minimal OR Material)"
    },
    {
      "key": "H",
      "name": "High",
      "description": "Mission Prevalence:Essential OR Public Well-Being Impact:(Irreversible)"
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/public_safety_impact_2_0_1.json
{
  "namespace": "ssvc",
  "version": "2.0.1",
  "key": "PSI",
  "name": "Public Safety Impact",
  "description": "A coarse-grained representation of impact to public safety.",
  "values": [
    {
      "key": "M",
      "name": "Minimal",
      "description": "Safety Impact:Negligible"
    },
    {
      "key": "S",
      "name": "Significant",
      "description": "Safety Impact:(Marginal OR Critical OR Catastrophic)"
    }
  ]
}
