=== CERTCC/SSVC/data/schema/Decision_Point.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Decision Point schema definition",
    "$id": "https://github.com/CERTCC/SSVC/tree/main/data/schema/Decision_Point.schema.json",
    "description": "Decision points are the basic building blocks of SSVC decision functions. Individual decision points describe a single aspect of the input to a decision function.",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "namespace": {
            "type": "string",
            "description": "Namespace (a short, unique string): For example, \"ssvc\" or \"cvss\" to indicate the source of the decision point"
        },
        "version": {
            "type": "string",
            "description": "Version (a semantic version string) that identifies this object"
        },
        "key": {
            "type": "string",
            "description": "A key (a short, unique string) that can be used to identify the Decision Point/Decision Point value in a shorthand way"
        },
        "name": {
            "type": "string",
            "description": "A short label that captures the description of the Decision Point or the Group of Decision Points."
        },
        "description": {
            "type": "string",
            "description": "Description of the Decision Point or the Group of Decision Points."
        },
        "values": {
            "description": "Decision Point Values are valid results from a Decision Point",
            "uniqueItems": true,
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "key": {
                        "type": "string",
                        "description": "A key (a short, unique string) that can be used to identify the Decision Point/Decision Point value in a shorthand way"
                    },
                    "name": {
                        "type": "string",
                        "description": "A short label that captures the description of the Decision Point or the Group of Decision Points."
                    },
                    "description": {
                        "type": "string",
                        "description": "Description of the Decision Point or the Group of Decision Points."
                    }
                }
            }
        }
    },
    "required": [
        "namespace",
        "version",
        "key",
        "name",
        "description",
        "values"
    ]
}

=== CERTCC/SSVC/data/json/decision_points/mission_impact_2_0_0.json
{
  "namespace": "ssvc",
  "version": "2.0.0",
  "key": "MI",
  "name": "Mission Impact",
  "description": "Impact on Mission Essential Functions of the Organization",
  "values": [
    {
      "key": "D",
      "name": "Degraded",
      "description": "Little to no impact up to degradation of non-essential functions; chronic degradation would eventually harm essential functions"
    },
    {
      "key": "MSC",
      "name": "MEF Support Crippled",
      "description": "Activities that directly support essential functions are crippled; essential functions continue for a time"
    },
    {
      "key": "MEF",
      "name": "MEF Failure",
      "description": "Any one mission essential function fails for period of time longer than acceptable; overall mission of the organization degraded but can still be accomplished for a time"
    },
    {
      "key": "MF",
      "name": "Mission Failure",
      "description": "Multiple or all mission essential functions fail; ability to recover those functions degraded; organization\u2019s ability to deliver its overall mission fails"
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/utility_1_0_0.json
{
  "namespace": "ssvc",
  "version": "1.0.0",
  "key": "U",
  "name": "Utility",
  "description": "The Usefulness of the Exploit to the Adversary",
  "values": [
    {
      "key": "L",
      "name": "Laborious",
      "description": "Virulence:Slow and Value Density:Diffuse"
    },
    {
      "key": "E",
      "name": "Efficient",
      "description": "Virulence:Rapid and Value Density:Diffuse OR Virulence:Slow and Value Density:Concentrated"
    },
    {
      "key": "S",
      "name": "Super Effective",
      "description": "Virulence:Rapid and Value Density:Concentrated"
    }
  ]
}

=== CERTCC/SSVC/docs/reference/examples/technical_impact.json
{
  "namespace": "ssvc",
  "version": "1.0.0",
  "name": "Technical Impact",
  "description": "The technical impact of the vulnerability.",
  "key": "TI",
  "values": [
    {
      "name": "Partial",
      "description": "The exploit gives the adversary limited control over, or information exposure about, the behavior of the software that contains the vulnerability. Or the exploit gives the adversary an importantly low stochastic opportunity for total control.",
      "key": "P"
    },
    {
      "name": "Total",
      "description": "The exploit gives the adversary total control over the behavior of the software, or it gives total disclosure of all information on the system that contains the vulnerability.",
      "key": "T"
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/public_safety_impact_2_0_0.json
{
  "namespace": "ssvc",
  "version": "2.0.0",
  "key": "PSI",
  "name": "Public Safety Impact",
  "description": "A coarse-grained representation of impact to public safety.",
  "values": [
    {
      "key": "M",
      "name": "Minimal",
      "description": "Safety Impact:(None OR Minor)"
    },
    {
      "key": "S",
      "name": "Significant",
      "description": "Safety Impact:(Major OR Hazardous OR Catastrophic)"
    }
  ]
}

=== CERTCC/SSVC/docs/reference/examples/human_impact.json
{
  "namespace": "ssvc",
  "version": "1.0.0",
  "name": "Human Impact",
  "description": "Human Impact",
  "key": "HI",
  "values": [
    {
      "name": "Low",
      "description": "Safety=None/Minor, Mission=None/Degraded/Crippled",
      "key": "L"
    },
    {
      "name": "Medium",
      "description": "Safety=None/Minor, Mission=MEF Failure OR Safety=Major, Mission=None/Degraded/Crippled",
      "key": "M"
    },
    {
      "name": "High",
      "description": "Safety=Hazardous, Mission=None/Degraded/Crippled/MEF Failure OR Safety=Major, Mission=MEF Failure",
      "key": "H"
    },
    {
      "name": "Very High",
      "description": "Safety=Catastrophic OR Mission=Mission Failure",
      "key": "VH"
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/safety_impact_1_0_0.json
{
  "namespace": "ssvc",
  "version": "1.0.0",
  "key": "SI",
  "name": "Safety Impact",
  "description": "The safety impact of the vulnerability.",
  "values": [
    {
      "key": "N",
      "name": "None",
      "description": "The effect is below the threshold for all aspects described in Minor."
    },
    {
      "key": "M",
      "name": "Minor",
      "description": "Any one or more of these conditions hold. Physical harm: Physical discomfort for users (not operators) of the system. Operator resiliency: Requires action by system operator to maintain safe system state as a result of exploitation of the vulnerability where operator actions would be well within expected operator abilities; OR causes a minor occupational safety hazard. System resiliency: Small reduction in built-in system safety margins; OR small reduction in system functional capabilities that support safe operation. Environment: Minor externalities (property damage, environmental damage, etc.) imposed on other parties. Financial Financial losses, which are not readily absorbable, to multiple persons. Psychological: Emotional or psychological harm, sufficient to be cause for counselling or therapy, to multiple persons."
    },
    {
      "key": "J",
      "name": "Major",
      "description": "Any one or more of these conditions hold. Physical harm: Physical distress and injuries for users (not operators) of the system. Operator resiliency: Requires action by system operator to maintain safe system state as a result of exploitation of the vulnerability where operator actions would be within their capabilities but the actions require their full attention and effort; OR significant distraction or discomfort to operators; OR causes significant occupational safety hazard. System resiliency: System safety margin effectively eliminated but no actual harm; OR failure of system functional capabilities that support safe operation. Environment: Major externalities (property damage, environmental damage, etc.) imposed on other parties. Financial: Financial losses that likely lead to bankruptcy of multiple persons. Psychological: Widespread emotional or psychological harm, sufficient to be cause for counselling or therapy, to populations of people."
    },
    {
      "key": "H",
      "name": "Hazardous",
      "description": "Any one or more of these conditions hold. Physical harm: Serious or fatal injuries, where fatalities are plausibly preventable via emergency services or other measures. Operator resiliency: Actions that would keep the system in a safe state are beyond system operator capabilities, resulting in adverse conditions; OR great physical distress to system operators such that they cannot be expected to operate the system properly. System resiliency: Parts of the cyber-physical system break; system\u2019s ability to recover lost functionality remains intact. Environment: Serious externalities (threat to life as well as property, widespread environmental damage, measurable public health risks, etc.) imposed on other parties. Financial: Socio-technical system (elections, financial grid, etc.) of which the affected component is a part is actively destabilized and enters unsafe state. Psychological: N/A."
    },
    {
      "key": "C",
      "name": "Catastrophic",
      "description": "Any one or more of these conditions hold. Physical harm: Multiple immediate fatalities (Emergency response probably cannot save the victims.) Operator resiliency: Operator incapacitated (includes fatality or otherwise incapacitated). System resiliency: Total loss of whole cyber-physical system, of which the software is a part. Environment: Extreme externalities (immediate public health threat, environmental damage leading to small ecosystem collapse, etc.) imposed on other parties. Financial: Social systems (elections, financial grid, etc.) supported by the software collapse. Psychological: N/A."
    }
  ]
}

=== CERTCC/SSVC/docs/reference/examples/supplier_contacted.json
{
  "namespace": "ssvc",
  "version": "1.0.0",
  "name": "Supplier Contacted",
  "description": "Has the reporter made a good-faith effort to contact the supplier of the vulnerable component using a quality contact method?",
  "key": "SC",
  "values": [
    {
      "name": "No",
      "description": "The supplier has not been contacted.",
      "key": "N"
    },
    {
      "name": "Yes",
      "description": "The supplier has been contacted.",
      "key": "Y"
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/public_value_added_1_0_0.json
{
  "namespace": "ssvc",
  "version": "1.0.0",
  "key": "PVA",
  "name": "Public Value Added",
  "description": "How much value would a publication from the coordinator benefit the broader community?",
  "values": [
    {
      "key": "P",
      "name": "Precedence",
      "description": "The publication would be the first publicly available, or be coincident with the first publicly available."
    },
    {
      "key": "A",
      "name": "Ampliative",
      "description": "Amplifies and/or augments the existing public information about the vulnerability, for example, adds additional detail, addresses or corrects errors in other public information, draws further attention to the vulnerability, etc."
    },
    {
      "key": "L",
      "name": "Limited",
      "description": "Minimal value added to the existing public information because existing information is already high quality and in multiple outlets."
    }
  ]
}
