=== CERTCC/SSVC/data/schema/SSVC_Computed.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://democert.org/ssvc/SVC_Computed_v2.03.schema.json",
    "title": "Computed SSVC score representing the path in the decision tree",
    "description": "This schema represents the full path in the decision tree taken by an analyst with a specific role.  The representation of the full decision tree is optional",
    "type": "object",
    "properties": {
	"computed": {
	    "type": "string",
	    "description": "An optional short vector representation of a SSV computed decision score.  This will be useful in providing permalink and other ways to provide quick read and access to a SSVC decision made"

	},
	"options": {
	    "type": "array",

	    "items": {
		"type": "object",
		"patternProperties": {
		    ".*": {
			"type": ["array","string"],
			"items": {
			    "type": "string"
			}
		    }
		}
	    },
	    "minItems": 1,
	    "uniqueItems": true		
	},
	"timestamp" : {
	    "description": "Date and time in ISO format  ISO 8601 format",
	    "type": "string",
	    "format": "date-time"
	},
	"role": {
	    "type": "string",
	    "description": "Roles are defined in SSVC spec and optional in SSVC provision schema"
	},
	"version": {
	    "type": "string",
	    "description":"Version of the SSVC that was used in this decision.  This version is of the semver format major.minor.patch The major.minor should identify SSVC version being used.  The specific tree being used should be in the patch numbet For example: \"Applier Tree 2.0.3\" would be the identity of the version of SSVC being \"2.0\" and the version of the Applier Tree to be \"3\"."
	},
	"decision_tree": {
	    "description": "The full decision tree that was used for this SSVC computed score",
	    "$ref": "https://democert.org/ssvc/SSVC_Provision_v2.03.schema.json"
	},
	"id": {
	    "type": "string",
	    "description": "Identifier for a vulnerbaility could be CVE, CERT/CC VU#, OSV id, Bugtraq etc."
	},
	"decision_tree_url": {
	    "type": "string",
	    "format": "uri",
	    "description": "A URL that points to the decision tree that was used to make this \"Computed\" decision"
	},
	"$schema": {
	    "type": "string",
	    "format": "uri",
	    "description": "A URL that points to the schema that was used for the decision tree that was used to make this \"Computed\" decision"
	},
	"generator": {
	    "type": "string",
	    "description": "Identify the software or tool that was used to generate this Computed JSON output.  Optionally append the version of the tool. ",
	    "examples": [
		"Dryad version 5.01.1"
		]
	}
	
    },
    "required": [
	"options",
	"timestamp",
	"role",
	"id",
	"version"
    ],
    "additionalProperties": false
}

=== CERTCC/SSVC/data/schema_examples/Computed-CVE-2014-0751-Coordinator-v2.0.2.json
{
    "role": "Coordinator",
    "id": "CVE-2014-0751",
    "version": "2.0",
    "computed": "SSVCv2/E:A/V:S/T:T/P:M/B:A/M:M/D:A/2021-09-29T15:29:44Z/",
    "timestamp": "2021-09-29T15:29:44Z",
    "options": [
	{
	    "Exploitation": "active"
	},
	{
	    "Virulence": "slow"
	},
	{
	    "Technical Impact": "total"
	},
	{
	    "Mission Prevalence": "Minimal"
	},
	{
	    "Public Well-being Impact": "Material"
	},
	{
	    "Mission & Well-being": "medium"
	}
    ],
    "$schema": "https://democert.org/ssvc/SSVC_Computed_v2.02.schema.json",
    "decision_tree_url": "https://democert.org/ssvc/CISA-Coordinator-v2.02.json"
}
