=== CERTCC/SSVC/data/schema/v2/Decision_Point_Value_Selection-2-0-0.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://certcc.github.io/SSVC/data/schema/v2/Decision_Point_Value_Selection-2-0-0.schema.json",
  "title": "Decision Point Value Selection List",
  "description": "This schema defines the structure for selecting SSVC Decision Points and their evaluated values for a given vulnerability. Each vulnerability can have multiple Decision Points, and each Decision Point can have multiple selected values when full certainty is not available.",
  "type": "object",
  "properties": {
    "timestamp": {
      "description": "Timestamp of the selections, in RFC 3339 format.",
      "examples": [
        "2025-01-01T12:00:00Z",
        "2025-01-02T15:30:45-04:00"
      ],
      "format": "date-time",
      "title": "Timestamp",
      "type": "string"
    },
    "schemaVersion": {
      "const": "2.0.0",
      "description": "The schema version of this selection list.",
      "title": "Schemaversion",
      "type": "string"
    },
    "target_ids": {
      "description": "Optional list of identifiers for the item or items (vulnerabilities, reports, advisories, systems, assets, etc.) being evaluated by these selections.",
      "examples": [
        [
          "CVE-1900-0000"
        ],
        [
          "VU#999999",
          "GHSA-0123-4567-89ab"
        ]
      ],
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "title": "Target Ids",
      "type": "array"
    },
    "selections": {
      "description": "List of selections made from decision points. Each selection item corresponds to value keys contained in a specific decision point identified by its namespace, key, and version. Note that selection objects are deliberately minimal objects and do not contain the full decision point details.",
      "items": {
        "$ref": "#/$defs/Selection"
      },
      "minItems": 1,
      "title": "Selections",
      "type": "array"
    },
    "resources": {
      "description": "A list of references to resources that provide additional context about the decision points found in this selection.",
      "examples": [
        [
          {
            "description": "Documentation for a set of decision points",
            "uri": "https://example.com/decision_points"
          },
          {
            "description": "JSON representation of decision point 2",
            "uri": "https://example.org/definitions/dp2.json"
          },
          {
            "description": "A JSON file containing extension decision points in the x_com.example namespace",
            "uri": "https://example.com/ssvc/x_com.example/decision_points.json"
          }
        ]
      ],
      "items": {
        "$ref": "#/$defs/Reference"
      },
      "minItems": 1,
      "title": "Resources",
      "type": "array"
    },
    "references": {
      "description": "A list of references to resources that provide additional context about the specific values selected.",
      "examples": [
        [
          {
            "description": "A report on which the selections were based",
            "uri": "https://example.com/report"
          }
        ]
      ],
      "items": {
        "$ref": "#/$defs/Reference"
      },
      "minItems": 1,
      "title": "References",
      "type": "array"
    }
  },
  "required": [
    "timestamp",
    "schemaVersion",
    "selections"
  ],
  "additionalProperties": false,
  "$defs": {
    "MinimalDecisionPointValue": {
      "description": "A minimal representation of a decision point value.",
      "properties": {
        "key": {
          "title": "Key",
          "type": "string"
        },
        "name": {
          "title": "Name",
          "type": "string"
        },
        "description": {
          "title": "Description",
          "type": "string"
        }
      },
      "required": [
        "key"
      ],
      "title": "MinimalDecisionPointValue",
      "type": "object"
    },
    "Reference": {
      "additionalProperties": false,
      "description": "A reference to a resource that provides additional context about the decision points or selections.",
      "properties": {
        "uri": {
          "format": "uri",
          "minLength": 1,
          "title": "Uri",
          "type": "string"
        },
        "description": {
          "title": "Description",
          "type": "string"
        }
      },
      "required": [
        "uri"
      ],
      "title": "Reference",
      "type": "object"
    },
    "Selection": {
      "additionalProperties": false,
      "description": "A minimal selection object that contains the decision point ID and the selected values.\nThis is used to transition from an SSVC decision point to a selection.\nOther fields like name and description may be copied from the decision point, but are not required.",
      "properties": {
        "name": {
          "title": "Name",
          "type": "string"
        },
        "description": {
          "title": "Description",
          "type": "string"
        },
        "namespace": {
          "description": "The namespace of the SSVC object.",
          "examples": [
            "ssvc",
            "cisa",
            "x_com.example//com.example#private",
            "ssvc/de-DE/example.organization#reference-arch-1"
          ],
          "maxLength": 1000,
          "minLength": 3,
          "pattern": "^(?=.{3,1000}$)(?:x_(?!.*[.-]{2,})[a-z][a-z0-9]+(?:[.-][a-z0-9]+)*|(?!.*[.-]{2,})[a-z][a-z0-9]+(?:[.-][a-z0-9]+)*)(?:(?:/(([A-Za-z]{2,3}(-[A-Za-z]{3}(-[A-Za-z]{3}){0,2})?|[A-Za-z]{4,8})(-[A-Za-z]{4})?(-([A-Za-z]{2}|[0-9]{3}))?(-([A-Za-z0-9]{5,8}|[0-9][A-Za-z0-9]{3}))*(-[A-WY-Za-wy-z0-9](-[A-Za-z0-9]{2,8})+)*(-[Xx](-[A-Za-z0-9]{1,8})+)?|[Xx](-[A-Za-z0-9]{1,8})+|[Ii]-[Dd][Ee][Ff][Aa][Uu][Ll][Tt]|[Ii]-[Mm][Ii][Nn][Gg][Oo])/|//)(?!.*[.-]{2,})[a-zA-Z][a-zA-Z0-9]*(?:[.-][a-zA-Z0-9]+)*(?:#[a-zA-Z0-9]+(?:[.-][a-zA-Z0-9]+)*)?(?:/(?!.*[.-]{2,})[a-zA-Z][a-zA-Z0-9]*(?:[.-][a-zA-Z0-9]+)*(?:#[a-zA-Z0-9]+(?:[.-][a-zA-Z0-9]+)*)?)*)?$",
          "title": "Namespace",
          "type": "string"
        },
        "key": {
          "title": "Key",
          "type": "string"
        },
        "version": {
          "default": "0.0.1",
          "description": "The version of the SSVC object. This must be a valid semantic version string.",
          "examples": [
            "1.0.0",
            "2.1.3"
          ],
          "minLength": 5,
          "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
          "title": "Version",
          "type": "string"
        },
        "values": {
          "description": "A list of selected value keys from the decision point values.",
          "examples": [
            [
              {
                "key": "N"
              },
              {
                "key": "Y"
              }
            ],
            [
              {
                "key": "A"
              },
              {
                "key": "B"
              },
              {
                "key": "C"
              }
            ]
          ],
          "items": {
            "$ref": "#/$defs/MinimalDecisionPointValue"
          },
          "minItems": 1,
          "title": "Values",
          "type": "array"
        }
      },
      "required": [
        "namespace",
        "key",
        "values"
      ],
      "title": "Selection",
      "type": "object"
    }
  }
}

=== CERTCC/SSVC/data/schema_examples/CVE-1900-1234-Decision_Point_Value_Selection-2-0-0.json
{
    "target_ids": ["CVE-1900-1234"],
    "timestamp": "2021-09-29T15:29:44Z",
    "schemaVersion": "2.0.0",
    "selections": [
	{
	    "namespace": "ssvc",
	    "name": "Exploitation",
	    "key": "E",
	    "version": "1.1.0",
	    "values": [
		{"name":"Active", "key": "A"}
	    ]
	},
	{
	    "namespace": "ssvc",
	    "name": "Automatable",
	    "key": "A",
	    "version": "2.0.0",
	    "values": [
		{"name": "Yes", "key": "Y"}
	    ]
	},
	{
	    "namespace": "ssvc",
	    "name": "Technical Impact",
	    "key": "TI",
	    "version": "1.0.0",
	    "values": [
		{"name": "Total","key":"T"}
	    ]
	}
    ]
}
